/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author SANG
 */
public class SinhVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form SinhVienPanel
     */
    public SinhVienPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("SINH VIEN");
        add(jLabel1);
        jLabel1.setBounds(364, 25, 268, 56);

        jLabel2.setText("MA SINH VIEN:");
        add(jLabel2);
        jLabel2.setBounds(87, 88, 109, 32);
        add(jTextField1);
        jTextField1.setBounds(226, 88, 280, 32);

        jLabel3.setText("TEN SINH VIEN:");
        add(jLabel3);
        jLabel3.setBounds(87, 127, 109, 32);
        add(jTextField2);
        jTextField2.setBounds(226, 127, 280, 32);

        jLabel4.setText("EMAIL:");
        add(jLabel4);
        jLabel4.setBounds(87, 177, 109, 32);
        add(jTextField3);
        jTextField3.setBounds(226, 177, 280, 32);

        jLabel5.setText("PHONE:");
        add(jLabel5);
        jLabel5.setBounds(87, 222, 109, 32);
        add(jTextField4);
        jTextField4.setBounds(226, 222, 280, 32);

        jLabel6.setText("GIOI TINH:");
        add(jLabel6);
        jLabel6.setBounds(87, 276, 109, 16);

        jRadioButton1.setText("NAM");
        add(jRadioButton1);
        jRadioButton1.setBounds(214, 272, 55, 25);

        jRadioButton2.setText("NU");
        add(jRadioButton2);
        jRadioButton2.setBounds(369, 272, 45, 25);

        jLabel7.setText("DIA CHI:");
        add(jLabel7);
        jLabel7.setBounds(90, 310, 70, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(220, 320, 290, 80);

        jLabel8.setText("jLabel8");
        add(jLabel8);
        jLabel8.setBounds(630, 120, 160, 210);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
