package models;
// Generated May 4, 2020 3:31:46 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name = "Sach",
        schema = "dbo",
        catalog = "Ontap"
        )
public class Sach  implements Serializable {


     private String maSach;
     private String tenSach;
     private Date ngayNhap;
     private Double giaTien;
     private Integer soLuong;
     private LoaiSach maLoaiSach;

    public Sach() {
    }

    public Sach(String maSach, String tenSach, Date ngayNhap, Double giaTien, Integer soLuong, LoaiSach maLoaiSach) {
        this.maSach = maSach;
        this.tenSach = tenSach;
        this.ngayNhap = ngayNhap;
        this.giaTien = giaTien;
        this.soLuong = soLuong;
        this.maLoaiSach = maLoaiSach;
    }

    @Id
    @Column(name = "maSach")
    public String getMaSach() {
        return maSach;
    }

    public void setMaSach(String maSach) {
        this.maSach = maSach;
    }

    @Column(name = "tenSach")
    public String getTenSach() {
        return tenSach;
    }

    public void setTenSach(String tenSach) {
        this.tenSach = tenSach;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngayNhap", length=10)
    public Date getNgayNhap() {
        return ngayNhap;
    }

    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }

    @Column(name = "giaTien")
    public Double getGiaTien() {
        return giaTien;
    }

    public void setGiaTien(Double giaTien) {
        this.giaTien = giaTien;
    }

    @Column(name = "soLuong")
    public Integer getSoLuong() {
        return soLuong;
    }

    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maLoaiSach")
    public LoaiSach getMaLoaiSach() {
        return maLoaiSach;
    }

    public void setMaLoaiSach(LoaiSach maLoaiSach) {
        this.maLoaiSach = maLoaiSach;
    }

    

}


