/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.QuanLyDiem;
import model.QuanLyDiemDAO;
import model.SinhVien;
import model.SinhVienDAO;

/**
 *
 * @author SANG
 */
public class QuanLyDiemPanel extends javax.swing.JPanel {
    SinhVienDAO svDAO = new SinhVienDAO();
    QuanLyDiemDAO dao = new QuanLyDiemDAO();
    static int rowId = 0;
    /**
     * Creates new form QuanLyDiemPanel
     */
    public QuanLyDiemPanel() {
        initComponents();
        getComboSinhVien();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboSinhVien = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiemTinHoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiemAnhVan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGiaoDucTC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThemmoi = new javax.swing.JButton();
        btnLuulai = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblDiemTrungBinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTable = new javax.swing.JTable();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ma SV :");

        cboSinhVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboSinhVienFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("SINH VIEN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ten SV :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("DIEM TIN HOC:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DIEM ANH VAN:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("GIAO DUC TC:");

        btnXoa.setText("XOA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThemmoi.setText("THEM MOI");
        btnThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmoiActionPerformed(evt);
            }
        });

        btnLuulai.setText("LUU LAI");
        btnLuulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuulaiActionPerformed(evt);
            }
        });

        btnSua.setText("SUA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("DIEM TRUNG BINH");

        lblDiemTrungBinh.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblDiemTrungBinh.setForeground(new java.awt.Color(0, 0, 153));
        lblDiemTrungBinh.setText("0.0");

        tbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma SV", "Ten SV", "TIN HOC", "ANH VAN", "GIAO DUC TC", "DIEM TRUNG BINH", "XEP LOAI"
            }
        ));
        tbTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTable);

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(cboSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiemTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiemAnhVan, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnThemmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnLuulai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtDiemTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtDiemAnhVan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFirst)
                            .addComponent(btnBack)
                            .addComponent(btnNext)
                            .addComponent(btnLast)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemmoi))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLuulai)
                                .addGap(25, 25, 25)
                                .addComponent(btnSua)
                                .addGap(25, 25, 25)
                                .addComponent(btnXoa)))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void reset(){
        txtMaSV.setText("");
        txtTenSV.setText("");
        txtDiemTinHoc.setText("");
        txtDiemAnhVan.setText("");
        txtGiaoDucTC.setText("");

    }
    public void getComboSinhVien(){
        DefaultComboBoxModel<SinhVien> model = (DefaultComboBoxModel) cboSinhVien.getModel();
        model.removeAllElements();
        for (SinhVien sv : svDAO.getAllSinhVien()) {
            model.addElement(sv);
        }
    }
    public void fillData(){
        DefaultTableModel tbModel = (DefaultTableModel) tbTable.getModel();
        tbModel.setRowCount(0);
        for (QuanLyDiem ql : dao.getAll()) {
            Object[] rowData = new Object[7];
            rowData[0] = ql.getSv().getMaSinhVien();
            rowData[1] = ql.getSv().getHotenSinhVien();
            rowData[2] = ql.getDiemTin();
            rowData[3] = ql.getDiemAnhVan();
            rowData[4] = ql.getDiemGDTC();
            String dtb = String.format("%.2f", ql.getDiemTB());
            rowData[5] = dtb;
            rowData[6] = ql.xepLoai();
            tbModel.addRow(rowData);
        }
    }
    public boolean validateForm(){
        if (txtMaSV.getText().isEmpty() || txtTenSV.getText().isEmpty() || txtDiemTinHoc.getText().isEmpty() || txtDiemAnhVan.getText().isEmpty() || txtGiaoDucTC.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    private void btnThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmoiActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnThemmoiActionPerformed

    private void cboSinhVienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboSinhVienFocusGained
        // TODO add your handling code here:
        getComboSinhVien();
    }//GEN-LAST:event_cboSinhVienFocusGained
    public QuanLyDiem getModel(){
        QuanLyDiem ql = new QuanLyDiem();
        ql.setSv(new SinhVien(txtMaSV.getText(), txtTenSV.getText()));
        ql.setDiemTin(Float.parseFloat(txtDiemTinHoc.getText()));
        ql.setDiemAnhVan(Float.parseFloat(txtDiemAnhVan.getText()));
        ql.setDiemGDTC(Float.parseFloat(txtGiaoDucTC.getText()));
        return ql;
    }
    public void setModel(QuanLyDiem ql){
        SinhVien sv = new SinhVien();
        txtMaSV.setText(ql.getSv().getMaSinhVien());
        txtTenSV.setText(ql.getSv().getHotenSinhVien());
        txtDiemTinHoc.setText(String.valueOf(ql.getDiemTin()));
        txtDiemAnhVan.setText(String.valueOf(ql.getDiemAnhVan()));
        txtGiaoDucTC.setText(String.valueOf(ql.getDiemGDTC()));
        String dtb = String.format("%.2f", ql.getDiemTB());
        lblDiemTrungBinh.setText(dtb);
    }
    public QuanLyDiem getAtPointDiem(int pos){
        QuanLyDiem ql = new QuanLyDiem();
        SinhVien sv = new SinhVien();
        sv.setMaSinhVien(tbTable.getValueAt(pos, 0).toString());
        sv.setHotenSinhVien(tbTable.getValueAt(pos, 1).toString());
        ql.setSv(sv);
        ql.setDiemTin(Float.parseFloat(tbTable.getValueAt(pos, 2).toString()));
        ql.setDiemAnhVan(Float.parseFloat(tbTable.getValueAt(pos, 3).toString()));
        ql.setDiemGDTC(Float.parseFloat(tbTable.getValueAt(pos, 4).toString()));
        return ql;
    }
    private void btnLuulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuulaiActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            QuanLyDiem q = getModel();
            if (dao.getQuanLyDiemByMaSV(q.getSv().getMaSinhVien()) != null) {
                JOptionPane.showMessageDialog(this, "ma sinh vien nay da ton tai");
            } else {
                if (dao.add(q) > 0) {
                    JOptionPane.showMessageDialog(this, "Luu thanh cong");
                    fillData();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xin vui long kiem tra thong tin");
        }
    }//GEN-LAST:event_btnLuulaiActionPerformed
//    public void setForm(int pos){
//        QuanLyDiem qldiem = dao.getDiem(pos);
//        txtMaSV.setText(qldiem.getSv().getMaSinhVien());
//        txtTenSV.setText(qldiem.getSv().getHotenSinhVien());
//        txtDiemTinHoc.setText(qldiem.getDiemTin()+"");
//        txtDiemAnhVan.setText(qldiem.getDiemAnhVan()+"");
//        txtGiaoDucTC.setText(qldiem.getDiemGDTC()+"");
//    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        SinhVien sv = (SinhVien)cboSinhVien.getSelectedItem();
        System.out.println("=>"+sv.toString());
        txtMaSV.setText(sv.getMaSinhVien());
        txtTenSV.setText(sv.getHotenSinhVien());
    }//GEN-LAST:event_btnAddActionPerformed

    private void tbTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableMouseClicked
        // TODO add your handling code here:
        rowId = tbTable.rowAtPoint(evt.getPoint());
        QuanLyDiem ql = getAtPointDiem(rowId);
        setModel(ql);
    }//GEN-LAST:event_tbTableMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (dao.del(txtMaSV.getText()) > 0) {
            JOptionPane.showMessageDialog(this, "Xoa thanh cong");
            fillData();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        QuanLyDiem ql = getModel();
        if (dao.edit(ql) > 0) {
            JOptionPane.showMessageDialog(this, "edit thanh cong");
            fillData();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
//        position = 0;
//        setForm(position);
          rowId = 0;
          QuanLyDiem ql = getAtPointDiem(rowId);
          setModel(ql);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//         TODO add your handling code here:
//        position--;
//        if (position < 0) {
//            position = 0;
//        }
//        setForm(position);
           rowId--;
           if (rowId <= 0) {
                rowId = 0;
            }
           QuanLyDiem ql = getAtPointDiem(rowId);
           setModel(ql);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
//        position++;
//        if (position >= dao.count()-1) {
//            position = dao.count()-1;
//        }
//        setForm(position);
            rowId++;
            if (rowId >= dao.getAll().size()-1) {
                 rowId = dao.getAll().size()-1;
            }
            QuanLyDiem ql = getAtPointDiem(rowId);
            setModel(ql);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
//        position = dao.count()-1;
//        if (position >= dao.count()-1) {
//            position = dao.count()-1;
//        }
//        setForm(position);
            rowId = dao.getAll().size()-1;
            QuanLyDiem ql = getAtPointDiem(rowId);
            setModel(ql);
    }//GEN-LAST:event_btnLastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLuulai;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemmoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboSinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemTrungBinh;
    private javax.swing.JTable tbTable;
    private javax.swing.JTextField txtDiemAnhVan;
    private javax.swing.JTextField txtDiemTinHoc;
    private javax.swing.JTextField txtGiaoDucTC;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTenSV;
    // End of variables declaration//GEN-END:variables
}
