/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import model.SinhVienDAO;

/**
 *
 * @author SANG
 */
public class SinhVienPanel extends javax.swing.JPanel {
    SinhVienDAO svd = new SinhVienDAO();
    File file = null;
    Image img = null;
    String strHinhanh = null;

    /**
     * Creates new form SinhVienPanel
     */
    public SinhVienPanel() {
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        lblHinhanh = new javax.swing.JLabel();
        btnLuuLai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUAN LY SINH VIEN");
        add(jLabel1);
        jLabel1.setBounds(339, 0, 265, 87);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("MA SINH VIEN:");
        add(jLabel2);
        jLabel2.setBounds(52, 90, 181, 29);
        add(txtMaSinhVien);
        txtMaSinhVien.setBounds(272, 91, 397, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("HO TEN:");
        add(jLabel3);
        jLabel3.setBounds(52, 135, 181, 37);
        add(txtHoTen);
        txtHoTen.setBounds(272, 135, 397, 37);
        add(txtEmail);
        txtEmail.setBounds(272, 179, 397, 37);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("EMAIL:");
        add(jLabel4);
        jLabel4.setBounds(52, 179, 181, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("SO DIEN THOAI:");
        add(jLabel5);
        jLabel5.setBounds(52, 229, 181, 37);
        add(txtPhone);
        txtPhone.setBounds(272, 234, 397, 37);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("GIOI TINH:");
        add(jLabel6);
        jLabel6.setBounds(52, 289, 181, 37);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("DIA CHI:");
        add(jLabel7);
        jLabel7.setBounds(52, 344, 181, 37);

        buttonGroup1.add(rdNam);
        rdNam.setText("NAM");
        add(rdNam);
        rdNam.setBounds(272, 300, 55, 25);

        buttonGroup1.add(rdNu);
        rdNu.setText("NU");
        add(rdNu);
        rdNu.setBounds(364, 300, 45, 25);

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 380, 610, 83);

        lblHinhanh.setText("HINH ANH");
        lblHinhanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHinhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhanhMouseClicked(evt);
            }
        });
        add(lblHinhanh);
        lblHinhanh.setBounds(820, 90, 210, 250);

        btnLuuLai.setText("LUU LAI");
        btnLuuLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLaiActionPerformed(evt);
            }
        });
        add(btnLuuLai);
        btnLuuLai.setBounds(940, 360, 100, 25);

        btnXoa.setText("XOA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(940, 390, 100, 25);

        btnThemMoi.setText("THEM MOI");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });
        add(btnThemMoi);
        btnThemMoi.setBounds(820, 360, 100, 25);

        btnSua.setText("SUA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(820, 390, 100, 25);

        tbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma sinh vien", "Ho ten", "Email", "So dien thoai", "Gioi tinh", "Dia chi", "Hinh anh"
            }
        ));
        tbTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(20, 540, 1060, 240);

        jLabel8.setText("TIM KIEM:");
        add(jLabel8);
        jLabel8.setBounds(70, 490, 70, 30);

        txtTimkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimkiemCaretUpdate(evt);
            }
        });
        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });
        add(txtTimkiem);
        txtTimkiem.setBounds(190, 482, 450, 40);

        btnThoat.setText("X");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        add(btnThoat);
        btnThoat.setBounds(1020, 5, 70, 40);
    }// </editor-fold>//GEN-END:initComponents
    public void reset(){
        txtMaSinhVien.setText("");
        txtHoTen.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        rdNam.setSelected(true);
        txtDiaChi.setText("");
    }
    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void lblHinhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhanhMouseClicked
        try {
            // TODO add your handling code here:
            JFileChooser fileChooser = new JFileChooser("C:\\Users\\SANG\\Documents\\NetBeansProjects\\AssIspace\\build\\classes\\images\\Hinh_Anh");
            fileChooser.showOpenDialog(null);
            file = fileChooser.getSelectedFile();
            System.out.println("file name"+file.toString());
            
            img = ImageIO.read(file);
            lblHinhanh.setText("");
            lblHinhanh.setIcon(new ImageIcon(img.getScaledInstance(lblHinhanh.getWidth(), lblHinhanh.getHeight(), 0)));
//            strHinhanh = file.getName();
        } catch (IOException ex) {
            Logger.getLogger(SinhVienPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_lblHinhanhMouseClicked
    public SinhVien getModel(){
        SinhVien sv = new SinhVien();
        sv.setMaSinhVien(txtMaSinhVien.getText().trim());
        sv.setHotenSinhVien(txtHoTen.getText().trim());
        sv.setEmail(txtEmail.getText());
        sv.setPhone(txtPhone.getText());
        boolean gt = false;
        if (rdNam.isSelected()) {
            gt = true;
        }
        sv.setGioitinh(gt);
        sv.setDiachi(txtDiaChi.getText().trim());
        if (file != null) {
            sv.setHinhanh(file.getName());
        } else {
            sv.setHinhanh("");
        }
        return sv;
    }
    public boolean validateform(){
        StringBuilder sb = new StringBuilder();
        if (txtMaSinhVien.getText().isEmpty()) {
            sb.append("Ban chua nhap ma sinh vien \n");
            txtMaSinhVien.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, sb);
            return false;
        } else {
            txtMaSinhVien.setBackground(Color.white);
        }
        if (txtHoTen.getText().isEmpty()) {
            sb.append("Ban chua nhap ho ten sinh vien \n");
            txtHoTen.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, sb);
            return false;
        } else {
            txtHoTen.setBackground(Color.white);
        }
        return true;
    }
    public void fillData(){
        DefaultTableModel tbModel = (DefaultTableModel) tbTable.getModel();
        tbModel.setRowCount(0);
        for (SinhVien sv : svd.getAllSinhVien()) {
            Object[] rowData = new Object[7];
            rowData[0] = sv.getMaSinhVien();
            rowData[1] = sv.getHotenSinhVien();
            rowData[2] = sv.getEmail();
            rowData[3] = sv.getPhone();
            String gt = "Nu";
            if (sv.isGioitinh()) {
                gt = "Nam";
            }
            rowData[4] = gt;
            rowData[5] = sv.getDiachi();
            rowData[6] = sv.getHinhanh();
            tbModel.addRow(rowData);
        }
    }
    public void setModel(SinhVien sv){
        int rowId = tbTable.getSelectedRow();
        txtMaSinhVien.setText(sv.getMaSinhVien());
        txtHoTen.setText(sv.getHotenSinhVien());
        txtEmail.setText(sv.getEmail());
        txtPhone.setText(sv.getPhone()+"");
        boolean gt = sv.isGioitinh();
        if (gt) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
        txtDiaChi.setText(sv.getDiachi());
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/Hinh_Anh/"+tbTable.getValueAt(rowId, 6).toString()));
        icon = new ImageIcon(icon.getImage().getScaledInstance(lblHinhanh.getWidth(), lblHinhanh.getHeight(), 0));
        lblHinhanh.setIcon(icon);
    }
//    public void fillDataFind(String find){
//        DefaultTableModel tbModel = (DefaultTableModel) tbTable.getModel();
//        tbModel.setRowCount(0);
//        for (SinhVien sv : svd.getFindSinhVien(find)) {
//            Object[] rowData = new Object[7];
//            rowData[0] = sv.getMaSinhVien();
//            rowData[1] = sv.getHotenSinhVien();
//            rowData[2] = sv.getEmail();
//            rowData[3] = sv.getPhone();
//            rowData[4] = sv.isGioitinh();
//            rowData[5] = sv.getDiachi();
//            rowData[6] = sv.getHinhanh();
//            tbModel.addRow(rowData);
//        }
//    }
    private void btnLuuLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLaiActionPerformed
        // TODO add your handling code here:
        if (validateform()) {
            SinhVien sv = getModel();
            if (svd.add(sv) > 0) {
                JOptionPane.showMessageDialog(this, "Luu thanh cong");
                fillData();
            }
        }
        
    }//GEN-LAST:event_btnLuuLaiActionPerformed

    private void tbTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableMouseClicked
        // TODO add your handling code here:
        int rowData = tbTable.rowAtPoint(evt.getPoint());
        txtMaSinhVien.setText(tbTable.getValueAt(rowData, 0).toString());
        txtHoTen.setText(tbTable.getValueAt(rowData, 1).toString());
        txtEmail.setText(tbTable.getValueAt(rowData, 2).toString());
        txtPhone.setText(tbTable.getValueAt(rowData, 3).toString());
        if (tbTable.getValueAt(rowData, 4).toString().equalsIgnoreCase("Nam")) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
        txtDiaChi.setText(tbTable.getValueAt(rowData, 5).toString());
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/Hinh_Anh/"+tbTable.getValueAt(rowData, 6).toString()));
        icon = new ImageIcon(icon.getImage().getScaledInstance(lblHinhanh.getWidth(), lblHinhanh.getHeight(), 0));
        lblHinhanh.setIcon(icon);
    }//GEN-LAST:event_tbTableMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (svd.del(txtMaSinhVien.getText()) > 0) {
            JOptionPane.showMessageDialog(this, "xoa thanh cong");
            fillData();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        SinhVien sv = getModel();
        if (svd.edit(sv) > 0) {
            JOptionPane.showMessageDialog(this, "sua thanh cong");
            fillData();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtTimkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimkiemCaretUpdate
        // TODO add your handling code here:
        String find = txtTimkiem.getText().trim();
//        fillDataFind(find);
    }//GEN-LAST:event_txtTimkiemCaretUpdate

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinhanh;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbTable;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
