package models;
// Generated May 6, 2020 8:40:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="Product"
    ,schema="dbo"
    ,catalog="ThiJaVa4"
)
public class Product  implements java.io.Serializable {


     private String maSp;
     private String tenSp;
     private Date ngayNhap;
     private Integer soLuong;
     private Double giaTien;

    public Product() {
    }

	
    public Product(String maSp) {
        this.maSp = maSp;
    }
    public Product(String maSp, String tenSp, Date ngayNhap, Integer soLuong, Double giaTien) {
       this.maSp = maSp;
       this.tenSp = tenSp;
       this.ngayNhap = ngayNhap;
       this.soLuong = soLuong;
       this.giaTien = giaTien;
    }
   
     @Id 

    
    @Column(name="maSP", unique=true, nullable=false)
    public String getMaSp() {
        return this.maSp;
    }
    
    public void setMaSp(String maSp) {
        this.maSp = maSp;
    }

    
    @Column(name="tenSP")
    public String getTenSp() {
        return this.tenSp;
    }
    
    public void setTenSp(String tenSp) {
        this.tenSp = tenSp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngayNhap", length=10)
    public Date getNgayNhap() {
        return this.ngayNhap;
    }
    
    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }

    
    @Column(name="soLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

    
    @Column(name="giaTien", precision=53, scale=0)
    public Double getGiaTien() {
        return this.giaTien;
    }
    
    public void setGiaTien(Double giaTien) {
        this.giaTien = giaTien;
    }




}


