package models;
// Generated May 5, 2020 9:06:11 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiSach generated by hbm2java
 */
@Entity
@Table(name="LoaiSach"
    ,schema="dbo"
    ,catalog="Ontap"
)
public class LoaiSach  implements Serializable {


     private int maLoaiSach;
     private String tenLoaiSach;


    public LoaiSach() {
    }

	
    public LoaiSach(int maLoaiSach) {
        this.maLoaiSach = maLoaiSach;
    }
    public LoaiSach(int maLoaiSach, String tenLoaiSach) {
       this.maLoaiSach = maLoaiSach;
       this.tenLoaiSach = tenLoaiSach;

    }
   
     @Id 

    
    @Column(name="maLoaiSach", unique=true, nullable=false)
    public int getMaLoaiSach() {
        return this.maLoaiSach;
    }
    
    public void setMaLoaiSach(int maLoaiSach) {
        this.maLoaiSach = maLoaiSach;
    }

    
    @Column(name="tenLoaiSach")
    public String getTenLoaiSach() {
        return this.tenLoaiSach;
    }
    
    public void setTenLoaiSach(String tenLoaiSach) {
        this.tenLoaiSach = tenLoaiSach;
    }

    @Override
    public String toString() {
        return "LoaiSach{" + "maLoaiSach=" + maLoaiSach + ", tenLoaiSach=" + tenLoaiSach + '}';
    }





}


