package models;
// Generated May 5, 2020 9:06:11 PM by Hibernate Tools 4.3.1



import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name="Sach"
    ,schema="dbo"
    ,catalog="Ontap"
)
public class Sach  implements Serializable {


     private String maSach;
     private LoaiSach loaiSach;
     private String tenSach;
     private Date ngayNhap;
     private Double giaTien;
     private Integer soLuong;

    public Sach() {
    }

	
    public Sach(String maSach) {
        this.maSach = maSach;
    }
    public Sach(String maSach, LoaiSach loaiSach, String tenSach, Date ngayNhap, Double giaTien, Integer soLuong) {
       this.maSach = maSach;
       this.loaiSach = loaiSach;
       this.tenSach = tenSach;
       this.ngayNhap = ngayNhap;
       this.giaTien = giaTien;
       this.soLuong = soLuong;
    }
   
     @Id 

    
    @Column(name="maSach", unique=true, nullable=false)
    public String getMaSach() {
        return this.maSach;
    }
    
    public void setMaSach(String maSach) {
        this.maSach = maSach;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maLoaiSach")
    public LoaiSach getLoaiSach() {
        return this.loaiSach;
    }
    
    public void setLoaiSach(LoaiSach loaiSach) {
        this.loaiSach = loaiSach;
    }

    
    @Column(name="tenSach")
    public String getTenSach() {
        return this.tenSach;
    }
    
    public void setTenSach(String tenSach) {
        this.tenSach = tenSach;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngayNhap", length=10)
    public Date getNgayNhap() {
        return this.ngayNhap;
    }
    
    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }

    
    @Column(name="giaTien", precision=53, scale=0)
    public Double getGiaTien() {
        return this.giaTien;
    }
    
    public void setGiaTien(Double giaTien) {
        this.giaTien = giaTien;
    }

    
    @Column(name="soLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }




}


